version: '3'

services:
  app:
    build: .
    command: npm start
    ports:
      - '3333:3333'
    volumes:
      - .:/usr/app 

  postgres:
    command: --init-file /docker/createDatabase.sql
    volumes:
      - ./docker/createDatabase.sql:/docker/createDatabase.sql
    image: postgres:11.2-alpine
    environment:
      POSTGRES_PASSWORD: postgres
