version: '3'

services:
  app:
    build: .
    ports:
      - '3333:3333'
    volumes:
      - .:/var/www/html/app
    depends_on:
      - db
    links:
      - db:localhost
    networks:
      - desgraca
    environment: 
      POSTGRES_HOST: postgres:postgres@db:5432

  db:
    volumes:
      - ./pgdata:/var/lib/postgres/data
    image: postgres
    ports:
      - '5432:5432'
    networks:
      - desgraca
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: user_api

volumes:
  pgdata:

networks:
  desgraca:
    driver: bridge
